In [81]:
import pandas as pd
import numpy as np
import seaborn as sns

In [83]:
df= pd.read_csv("C:/Users/VINAY KUMAR PATEL/Downloads/machine learning/diabetes__1_.csv",header=0)

In [85]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [87]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [89]:
x=df.loc[:,df.columns!="Outcome"]

In [91]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [93]:
y= df['Outcome']

In [95]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

# test train split

In [98]:
from  sklearn.model_selection  import train_test_split

In [100]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [102]:
x_train.shape

(614, 8)

In [104]:
x_test.shape

(154, 8)

# tree making

In [107]:
from sklearn import tree
cls_tree=tree.DecisionTreeClassifier(max_depth=3)
cls_tree.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3)

# predicting value

In [110]:
y_train_pred= cls_tree.predict(x_train)
y_train_pred

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,

In [112]:
y_test_pred= cls_tree.predict(x_test)
y_test_pred

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
      dtype=int64)

In [114]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [116]:
confusion_matrix(y_train , y_train_pred )

array([[337,  56],
       [ 89, 132]], dtype=int64)

In [118]:
confusion_matrix(y_test , y_test_pred )

array([[93, 14],
       [23, 24]], dtype=int64)

In [120]:
accuracy_score(y_train , y_train_pred )

0.7638436482084691

In [122]:
accuracy_score(y_test , y_test_pred )

0.7597402597402597

# ploting decision tree

In [125]:
dot_data = tree.export_graphviz(cls_tree,out_file = None,feature_names =x_train.columns,filled= True)

In [127]:
from IPython.display import Image

In [129]:
import pydotplus

In [131]:
graph= pydotplus.graph_from_dot_data(dot_data)

In [132]:
Image(graph.create_png())

# bagging 

In [135]:
from sklearn import tree
clftree=tree.DecisionTreeClassifier()

In [136]:
from sklearn.ensemble import BaggingClassifier

In [137]:
bag_clf = BaggingClassifier(estimator = clftree,n_estimators =1000,bootstrap= True,n_jobs=-1,random_state=42)

In [138]:
bag_clf.fit(x_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=1000,
                  n_jobs=-1, random_state=42)

In [139]:
confusion_matrix(y_test , y_test_pred )

array([[93, 14],
       [23, 24]], dtype=int64)

In [140]:
accuracy_score(y_test , y_test_pred )

0.7597402597402597

In [145]:
accuracy_score(y_train , y_train_pred )

0.7638436482084691

# random forest

In [147]:
from sklearn.ensemble import RandomForestClassifier

In [148]:
rf_clf = RandomForestClassifier(n_estimators = 1000,n_jobs=-1,random_state=42)

In [149]:
rf_clf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=1000, n_jobs=-1, random_state=42)

In [150]:
accuracy_score(y_test , y_test_pred )

0.7597402597402597

In [151]:
accuracy_score(y_train , y_train_pred )

0.7638436482084691

In [161]:
confusion_matrix(y_test , y_test_pred )

array([[93, 14],
       [23, 24]], dtype=int64)

# gradient boost

In [103]:
from sklearn.ensemble import GradientBoostingClassifier

In [105]:
gbc_clf= GradientBoostingClassifier(learning_rate=0.2,n_estimators = 1000,max_depth=1)

In [107]:
gbc_clf.fit(x_train,y_train)

GradientBoostingClassifier(learning_rate=0.2, max_depth=1, n_estimators=1000)

In [108]:
accuracy_score(y_test,gbc_clf.predict(x_test))

0.7987012987012987

In [111]:
accuracy_score(y_train,gbc_clf.predict(x_train))

0.8664495114006515

# ada boost

In [114]:
from sklearn.ensemble import AdaBoostClassifier

In [116]:
ada_clf= AdaBoostClassifier(n_estimators = 5000)

In [118]:
ada_clf.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(n_estimators=5000)

In [119]:
accuracy_score(y_test,ada_clf.predict(x_test))

0.7272727272727273

In [120]:
accuracy_score(y_train,gbc_clf.predict(x_train))

0.8664495114006515

In [124]:
ada_clf_1= AdaBoostClassifier(n_estimators = 500)
ada_clf_1.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier(n_estimators=500)

In [126]:
accuracy_score(y_test,ada_clf_1.predict(x_test))

0.8051948051948052

In [128]:
accuracy_score(y_train,gbc_clf.predict(x_train))

0.8664495114006515

# xg boost

In [131]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [132]:
import xgboost as xgb

In [133]:
xgb_clf=xgb.XGBClassifier(max_depth=5,n_estimators=1000,learning_rate=0.2)

In [137]:
xgb_clf.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [138]:
accuracy_score(y_test,xgb_clf.predict(x_test))

0.7727272727272727

In [141]:
accuracy_score(y_train,xgb_clf.predict(x_train))

1.0

In [143]:
xgb_clf2=xgb.XGBClassifier(max_depth=5,n_estimators=10000,learning_rate=0.2)

In [145]:
xgb_clf2.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=10000, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [146]:
accuracy_score(y_train,xgb_clf2.predict(x_train))

1.0

In [147]:
accuracy_score(y_test,xgb_clf2.predict(x_test))

0.7792207792207793

In [149]:
xgb_clf3=xgb.XGBClassifier(max_depth=5,n_estimators=1000,learning_rate=0.2)

In [153]:
xgb_clf3.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.2, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [154]:
accuracy_score(y_test,xgb_clf3.predict(x_test))

0.7727272727272727

In [155]:
accuracy_score(y_train,xgb_clf3.predict(x_train))

1.0